RELEASE_DIR=${TMP_DIR}/nokore

.PHONY : luacheck
luacheck:
	luacheck .

# Release step specifically when the modpack is under a game, this will copy
# the modpack to the TMP_DIR
.PHONY: prepare.release
prepare.release:
	mkdir -p "${RELEASE_DIR}"

	cp -r --parents nokore_apple "${RELEASE_DIR}"
	cp -r --parents nokore_backpacks "${RELEASE_DIR}"
	cp -r --parents nokore_bed "${RELEASE_DIR}"
	cp -r --parents nokore_biome "${RELEASE_DIR}"
	cp -r --parents nokore_biome_bamboo_forest "${RELEASE_DIR}"
	cp -r --parents nokore_biome_coniferous_forest "${RELEASE_DIR}"
	cp -r --parents nokore_biome_deciduous_forest "${RELEASE_DIR}"
	cp -r --parents nokore_biome_desert "${RELEASE_DIR}"
	cp -r --parents nokore_biome_grassland "${RELEASE_DIR}"
	cp -r --parents nokore_biome_icesheet "${RELEASE_DIR}"
	cp -r --parents nokore_biome_mushroom_forest "${RELEASE_DIR}"
	cp -r --parents nokore_biome_rainforest "${RELEASE_DIR}"
	cp -r --parents nokore_biome_sakura_forest "${RELEASE_DIR}"
	cp -r --parents nokore_biome_savanna "${RELEASE_DIR}"
	cp -r --parents nokore_biome_snowy_grassland "${RELEASE_DIR}"
	cp -r --parents nokore_biome_taiga "${RELEASE_DIR}"
	cp -r --parents nokore_biome_tundra "${RELEASE_DIR}"
	cp -r --parents nokore_block_data "${RELEASE_DIR}"
	cp -r --parents nokore_book "${RELEASE_DIR}"
	cp -r --parents nokore_bookshelf "${RELEASE_DIR}"
	cp -r --parents nokore_chest "${RELEASE_DIR}"
	cp -r --parents nokore_common "${RELEASE_DIR}"
	cp -r --parents nokore_creative "${RELEASE_DIR}"
	cp -r --parents nokore_door "${RELEASE_DIR}"
	cp -r --parents nokore_dye "${RELEASE_DIR}"
	cp -r --parents nokore_entity_walkover "${RELEASE_DIR}"
	cp -r --parents nokore_furnace "${RELEASE_DIR}"
	cp -r --parents nokore_game_data "${RELEASE_DIR}"
	cp -r --parents nokore_glass "${RELEASE_DIR}"
	cp -r --parents nokore_gunpowder "${RELEASE_DIR}"
	cp -r --parents nokore_mapgen "${RELEASE_DIR}"
	cp -r --parents nokore_mapgen_decor_coral "${RELEASE_DIR}"
	cp -r --parents nokore_mapgen_decor_flower "${RELEASE_DIR}"
	cp -r --parents nokore_mapgen_decor_giant_mushroom "${RELEASE_DIR}"
	cp -r --parents nokore_mapgen_decor_tree_acacia "${RELEASE_DIR}"
	cp -r --parents nokore_mapgen_decor_tree_big_oak "${RELEASE_DIR}"
	cp -r --parents nokore_mapgen_decor_tree_birch "${RELEASE_DIR}"
	cp -r --parents nokore_mapgen_decor_tree_jungle "${RELEASE_DIR}"
	cp -r --parents nokore_mapgen_decor_tree_oak "${RELEASE_DIR}"
	cp -r --parents nokore_mapgen_decor_tree_sakura "${RELEASE_DIR}"
	cp -r --parents nokore_mapgen_decor_tree_spruce "${RELEASE_DIR}"
	cp -r --parents nokore_mapgen_lava "${RELEASE_DIR}"
	cp -r --parents nokore_mapgen_sand "${RELEASE_DIR}"
	cp -r --parents nokore_mapgen_snow "${RELEASE_DIR}"
	cp -r --parents nokore_mapgen_standard "${RELEASE_DIR}"
	cp -r --parents nokore_mapgen_water "${RELEASE_DIR}"
	cp -r --parents nokore_ore_clay "${RELEASE_DIR}"
	cp -r --parents nokore_ore_coal "${RELEASE_DIR}"
	cp -r --parents nokore_ore_copper "${RELEASE_DIR}"
	cp -r --parents nokore_ore_gold "${RELEASE_DIR}"
	cp -r --parents nokore_ore_iron "${RELEASE_DIR}"
	cp -r --parents nokore_ore_tin "${RELEASE_DIR}"
	cp -r --parents nokore_player_data "${RELEASE_DIR}"
	cp -r --parents nokore_player_hud "${RELEASE_DIR}"
	cp -r --parents nokore_player_inv "${RELEASE_DIR}"
	cp -r --parents nokore_player_inv10 "${RELEASE_DIR}"
	cp -r --parents nokore_player_service "${RELEASE_DIR}"
	cp -r --parents nokore_player_spawn "${RELEASE_DIR}"
	cp -r --parents nokore_player_stats "${RELEASE_DIR}"
	cp -r --parents nokore_proxy "${RELEASE_DIR}"
	cp -r --parents nokore_rail "${RELEASE_DIR}"
	cp -r --parents nokore_sieve "${RELEASE_DIR}"
	cp -r --parents nokore_stairs "${RELEASE_DIR}"
	cp -r --parents nokore_stockpile "${RELEASE_DIR}"
	cp -r --parents nokore_tnt "${RELEASE_DIR}"
	cp -r --parents nokore_tool "${RELEASE_DIR}"
	cp -r --parents nokore_tool_bronze "${RELEASE_DIR}"
	cp -r --parents nokore_tool_copper "${RELEASE_DIR}"
	cp -r --parents nokore_tool_iron "${RELEASE_DIR}"
	cp -r --parents nokore_tool_steel "${RELEASE_DIR}"
	cp -r --parents nokore_tool_stone "${RELEASE_DIR}"
	cp -r --parents nokore_treasure "${RELEASE_DIR}"
	cp -r --parents nokore_ui "${RELEASE_DIR}"
	cp -r --parents nokore_wool "${RELEASE_DIR}"
	cp -r --parents nokore_wool_mat "${RELEASE_DIR}"
	cp -r --parents nokore_world_bamboo "${RELEASE_DIR}"
	cp -r --parents nokore_world_bone "${RELEASE_DIR}"
	cp -r --parents nokore_world_cactus "${RELEASE_DIR}"
	cp -r --parents nokore_world_clay "${RELEASE_DIR}"
	cp -r --parents nokore_world_coal "${RELEASE_DIR}"
	cp -r --parents nokore_world_cobweb "${RELEASE_DIR}"
	cp -r --parents nokore_world_copper "${RELEASE_DIR}"
	cp -r --parents nokore_world_coral "${RELEASE_DIR}"
	cp -r --parents nokore_world_core "${RELEASE_DIR}"
	cp -r --parents nokore_world_fern "${RELEASE_DIR}"
	cp -r --parents nokore_world_flower "${RELEASE_DIR}"
	cp -r --parents nokore_world_giant_mushroom "${RELEASE_DIR}"
	cp -r --parents nokore_world_gold "${RELEASE_DIR}"
	cp -r --parents nokore_world_grass "${RELEASE_DIR}"
	cp -r --parents nokore_world_iron "${RELEASE_DIR}"
	cp -r --parents nokore_world_lava "${RELEASE_DIR}"
	cp -r --parents nokore_world_melon "${RELEASE_DIR}"
	cp -r --parents nokore_world_mushroom "${RELEASE_DIR}"
	cp -r --parents nokore_world_pumpkin "${RELEASE_DIR}"
	cp -r --parents nokore_world_quartz "${RELEASE_DIR}"
	cp -r --parents nokore_world_reed "${RELEASE_DIR}"
	cp -r --parents nokore_world_snow "${RELEASE_DIR}"
	cp -r --parents nokore_world_sponge "${RELEASE_DIR}"
	cp -r --parents nokore_world_standard "${RELEASE_DIR}"
	cp -r --parents nokore_world_steel "${RELEASE_DIR}"
	cp -r --parents nokore_world_tin "${RELEASE_DIR}"
	cp -r --parents nokore_world_tree_acacia "${RELEASE_DIR}"
	cp -r --parents nokore_world_tree_big_oak "${RELEASE_DIR}"
	cp -r --parents nokore_world_tree_birch "${RELEASE_DIR}"
	cp -r --parents nokore_world_tree_fir "${RELEASE_DIR}"
	cp -r --parents nokore_world_tree_jungle "${RELEASE_DIR}"
	cp -r --parents nokore_world_tree_oak "${RELEASE_DIR}"
	cp -r --parents nokore_world_tree_sakura "${RELEASE_DIR}"
	cp -r --parents nokore_world_tree_spruce "${RELEASE_DIR}"
	cp -r --parents nokore_world_tree_willow "${RELEASE_DIR}"
	cp -r --parents nokore_world_vine "${RELEASE_DIR}"
	cp -r --parents nokore_world_water "${RELEASE_DIR}"
	cp -r --parents nokore_world_waterlily "${RELEASE_DIR}"

	cp LICENSE "${RELEASE_DIR}"
	cp modpack.conf "${RELEASE_DIR}"
	cp README.md "${RELEASE_DIR}"
