name = nokore_furnace
depends = foundation_base,foundation_formspec,foundation_headless,foundation_inv,foundation_stdlib,nokore_common,nokore_ui,nokore_player_inv
optional_depends = nokore_prelude,yatm_autotest,yatm_item_storage
